# permissions for end users to view containerappinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerappinstance-viewer-role
rules:
- apiGroups:
  - ce.app.klh.com
  resources:
  - containerappinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ce.app.klh.com
  resources:
  - containerappinstances/status
  verbs:
  - get
